autoIndex = true

[[articles]]
name = "language"
title = "The Language Specification"

[[articles]]
name = "builtin"
title = "Builtin Functions and Variables"

[[articles]]
name = "edit"
title = "edit: API for the Interactive Editor"

[[articles]]
name = "epm"
title = "epm: The Elvish Package Manager"

[[articles]]
name = "math"
title = "math: Math Utilities"

[[articles]]
name = "platform"
title = "platform: Information About the Platform"

[[articles]]
name = "re"
title = "re: Regular Expression Utilities"

[[articles]]
name = "readline-binding"
title = "readline-binding: Readline-like Key Bindings"

[[articles]]
name = "store"
title = "store: API for the Elvish Persistent Data Store"

[[articles]]
name = "str"
title = "str: String Manipulation"

[[articles]]
name = "unix"
title = "unix: Support for UNIX-like systems"
