autoIndex = true
prelude = "prelude"

[[articles]]
name = "language"
title = "Language Specification"
group = -1

[[articles]]
name = "command"
title = "The Elvish Command"
group = -1

[[groups]]
intro = """
Modules in the Elvish standard library:
"""

[[articles]]
name = "builtin"
title = "Builtin Functions and Variables"

[[articles]]
name = "doc"
title = "doc: Documentation of Elvish modules"

[[articles]]
name = "edit"
title = "edit: API for the Interactive Editor"

[[articles]]
name = "epm"
title = "epm: The Elvish Package Manager"

[[articles]]
name = "flag"
title = "flag: Command-line flag parsing"

[[articles]]
name = "file"
title = "file: File Utilities"

[[articles]]
name = "math"
title = "math: Math Utilities"

[[articles]]
name = "os"
title = "os: Operating system functionality"

[[articles]]
name = "path"
title = "path: Filesystem Path Utilities"

[[articles]]
name = "platform"
title = "platform: Information About the Platform"

[[articles]]
name = "re"
title = "re: Regular Expression Utilities"

[[articles]]
name = "readline-binding"
title = "readline-binding: Readline-like Key Bindings"

[[articles]]
name = "runtime"
title = "runtime: Information About the Elvish Runtime"

[[articles]]
name = "store"
title = "store: API for the Elvish Persistent Data Store"

[[articles]]
name = "str"
title = "str: String Manipulation"

[[articles]]
name = "unix"
title = "unix: Support for UNIX-like systems"
