title = "Elvish Shell"
author = "Qi Xiao"
feedPosts = 10
template = "template.html"
baseCSS = ["style.css", "fonts.css"]
rootURL = "https://elv.sh"

[index]
name = "home"
extraCSS = ["icon-font.css", "home.css"]
extraJS = ["home.js"]

[[categories]]
name = "get"
title = "Get Elvish"

[[categories]]
name = "learn"
title = "Learn Elvish"

[[categories]]
name = "ref"
title = "Elvish Reference"

[[categories]]
name = "blog"
title = "Elvish Blog"
