[[articles]]
name = "0.12-release-notes"
title = "Elvish 0.12 Release Notes"
timestamp = "2018-08-01"

[[articles]]
name = "0.11-release-notes"
title = "Elvish 0.11 Release Notes"
timestamp = "2018-01-17"

[[articles]]
name = "newsletter-sep-2017"
title = "Elvish Newsletter, Sep 2017 Issue"
timestamp = "2017-09-17"

[[articles]]
name = "0.10-release-notes"
title = "Elvish 0.10 Release Notes"
timestamp = "2017-09-17"

[[articles]]
name = "newsletter-july-2017"
title = "Elvish Newsletter, July 2017 Issue"
timestamp = "2017-07-10"

[[articles]]
name = "0.9-release-notes"
title = "Elvish 0.9 Release Notes"
timestamp = "2017-07-03"

[[articles]]
name = "live"
title = "The Elvish Website is Officially Live!"
timestamp = "2017-07-03"
